# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20160130_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrepair',
            name='part_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name=b'Unit Cost'),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='part_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Part Name'),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='part_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=b'Part Number'),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='part_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Quantity'),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='part_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name=b'Part Supplier'),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='po_num',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=b'PO Number'),
        ),
    ]
