# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20160214_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinfo',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_types', to='equipment.EquipmentType', verbose_name=b'Equipment Type'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='manufacturer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_manufacturer', to='equipment.EquipmentManufacturer', verbose_name=b'Manufacturer Name'),
        ),
    ]
