# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20160229_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='equipment_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentClass', verbose_name=b'Equipment Class'),
            preserve_default=False,
        ),
    ]
