# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_equipmenttype_equipment_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='tooltip_content',
            field=models.CharField(default=b'', max_length=256, null=True, verbose_name=b'Tooltip'),
        ),
    ]
