# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipmentclass_tooltip_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinfo',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Parent ID'),
        ),
        migrations.AddField(
            model_name='equipmentinfo',
            name='prod_workcell_master',
            field=models.BooleanField(default=False, verbose_name=b'Production Workcell Master'),
        ),
    ]
