# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20160214_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='IsSharedLM',
            field=models.BooleanField(default=False, verbose_name=b'Is Shared LM Name'),
        ),
    ]
