# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20150731_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpm',
            name='Date_Performed',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date Performed'),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='Date_Performed',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date Performed'),
        ),
    ]
