# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20160221_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name=b'Group Name')),
            ],
            options={
                'verbose_name': 'Equipment - Class',
                'verbose_name_plural': 'Equipment - Class',
            },
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentType', verbose_name=b'Equipment Type'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='manufacturer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentManufacturer', verbose_name=b'Manufacturer Name'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='part_identifier',
            field=models.CharField(max_length=25, verbose_name=b'Machine ID (alias)'),
        ),
        migrations.AlterField(
            model_name='equipmentmanufacturer',
            name='manufacturer_name',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'Manufacturer Name'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='equipment_type',
            field=models.CharField(max_length=50, unique=True, verbose_name=b'Equipment Type'),
        ),
    ]
