# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0006_auto_20160618_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('uut_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(choices=[('Round Sheet', 'Round Sheet'), ('Startup Shot', 'Startup Shot'), ('System', 'System'), ('Custom', 'Custom')], max_length=35)),
                ('product_type', models.CharField(choices=[('IMM', 'Injection Mold'), ('ISBM', 'Injection Stretch Blow Mold'), ('FAS', 'Assembly'), ('OFP', 'Print')], max_length=35)),
                ('job_number', models.CharField(max_length=20, verbose_name='Job Number')),
                ('production_date', models.DateField(verbose_name='Production Date')),
                ('start_date_time', models.DateTimeField(verbose_name='Inspection Start Date-Time')),
                ('part_number', models.CharField(max_length=20, verbose_name='Part Number')),
                ('mold_number', models.CharField(max_length=20, verbose_name='Mold Number')),
                ('sta_reported', models.CharField(max_length=5, verbose_name='STA Reported')),
                ('shift', models.CharField(max_length=5, verbose_name='Shift')),
                ('inspection_result', models.IntegerField(verbose_name='Inspection Result')),
                ('location', models.CharField(choices=[('Somerville', 'Somerville'), ('Brantford', 'Brantford')], max_length=20)),
            ],
            options={
                'verbose_name': 'Inspection: Top Level',
                'verbose_name_plural': 'Inspections: Top Level',
            },
        ),
        migrations.CreateModel(
            name='PropBool',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prop_result', models.IntegerField(verbose_name='Prop Result')),
                ('date_time', models.DateTimeField(verbose_name='Prop Date-Time')),
                ('cav_id', models.CharField(max_length=5, verbose_name='Cavity ID')),
                ('head_id', models.CharField(max_length=5, verbose_name='Head ID')),
            ],
            options={
                'verbose_name': 'Inspection: Step Property Boolean',
                'verbose_name_plural': 'Inspections: Step Property Boolean',
            },
        ),
        migrations.CreateModel(
            name='PropFloat',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prop_value', models.FloatField(verbose_name='Value')),
                ('prop_result', models.IntegerField(verbose_name='Prop Result')),
                ('date_time', models.DateTimeField(verbose_name='Prop Date-Time')),
                ('cav_id', models.CharField(max_length=5, verbose_name='Cavity ID')),
                ('head_id', models.CharField(max_length=5, verbose_name='Head ID')),
            ],
            options={
                'verbose_name': 'Inspection: Step Property Float',
                'verbose_name_plural': 'Inspections: Step Property Float',
            },
        ),
        migrations.CreateModel(
            name='PropInt',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prop_value', models.IntegerField(verbose_name='Value')),
                ('prop_result', models.IntegerField(verbose_name='Prop Result')),
                ('date_time', models.DateTimeField(verbose_name='Prop Date-Time')),
                ('cav_id', models.CharField(max_length=5, verbose_name='Cavity ID')),
                ('head_id', models.CharField(max_length=5, verbose_name='Head ID')),
            ],
            options={
                'verbose_name': 'Inspection: Step Property Int',
                'verbose_name_plural': 'Inspections: Step Property Int',
            },
        ),
        migrations.CreateModel(
            name='PropNumericLimit',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prop_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Value')),
                ('low_limit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Low Limit')),
                ('high_limit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='High Limit')),
                ('prop_result', models.IntegerField(verbose_name='Prop Result')),
                ('date_time', models.DateTimeField(verbose_name='Prop Date-Time')),
                ('cav_id', models.CharField(max_length=5, verbose_name='Cavity ID')),
                ('head_id', models.CharField(max_length=5, verbose_name='Head ID')),
            ],
            options={
                'verbose_name': 'Inspection: Step Property Numeric Limit',
                'verbose_name_plural': 'Inspections: Step Property Numeric Limit',
            },
        ),
        migrations.CreateModel(
            name='PropText',
            fields=[
                ('prop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prop_value', models.CharField(max_length=75, verbose_name='Value')),
                ('prop_result', models.IntegerField(verbose_name='Prop Result')),
                ('date_time', models.DateTimeField(verbose_name='Prop Date-Time')),
                ('cav_id', models.CharField(max_length=5, verbose_name='Cavity ID')),
                ('head_id', models.CharField(max_length=5, verbose_name='Head ID')),
            ],
            options={
                'verbose_name': 'Inspection: Step Property Text',
                'verbose_name_plural': 'Inspections: Step Property Text',
            },
        ),
        migrations.CreateModel(
            name='StaticInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_description_short', models.CharField(max_length=25, verbose_name='Short Description')),
                ('tag_description_desc', models.CharField(max_length=200, verbose_name='Long Description')),
                ('inspection_type', models.CharField(choices=[('Numeric Limit', 'Numeric Limit'), ('Float', 'Float'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('Text', 'Text')], max_length=25)),
            ],
            options={
                'verbose_name': 'Static Inspection Steps ',
                'verbose_name_plural': 'Static Inspection Regime Steps',
            },
        ),
        migrations.CreateModel(
            name='StaticInspectionBool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_short', models.CharField(max_length=25)),
                ('reason_long', models.CharField(max_length=200)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.Part', to_field='item_Number')),
                ('static_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection')),
            ],
            options={
                'verbose_name': 'Static Inspection Step Boolean',
                'verbose_name_plural': 'Static Inspections Boolean',
            },
        ),
        migrations.CreateModel(
            name='StaticInspectionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_name_short', models.CharField(max_length=25, verbose_name='Inspection Group')),
                ('inspection_name_desc', models.CharField(max_length=200, verbose_name='Inspection Group Description')),
                ('product_type', models.CharField(choices=[('A', 'All'), ('M', 'Mold'), ('IMM', 'Injection Mold'), ('ISBM', 'Injection Stretch Blow Mold'), ('FAS', 'Assembly'), ('OFP', 'Print')], max_length=25, verbose_name='Product Type')),
                ('apply_type', models.CharField(choices=[('All', 'All'), ('Type', 'Type Specific'), ('Part', 'Part Specific')], max_length=10, verbose_name='Apply to all parts in product type?')),
                ('location', models.CharField(choices=[('Somerville', 'Somerville'), ('Brantford', 'Brantford')], max_length=20)),
            ],
            options={
                'verbose_name': 'Static Inspection Regime',
                'verbose_name_plural': 'Static Inspection Regimes',
            },
        ),
        migrations.CreateModel(
            name='StaticInspectionLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('low_limit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Low Limit')),
                ('high_limit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='High Limit')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.Part', to_field='item_Number')),
                ('static_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection')),
            ],
            options={
                'verbose_name': 'Static Inspections Step Limit',
                'verbose_name_plural': 'Static Inspection Step Limits',
            },
        ),
        migrations.CreateModel(
            name='StaticInspectionPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspectionGroup')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.Part', to_field='item_Number')),
            ],
            options={
                'verbose_name': 'Station Inspection Steps - Part Assignment',
                'verbose_name_plural': 'Station Inspection Steps - Part Assignments',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_result', models.IntegerField(verbose_name='Step Result')),
                ('start_date_time', models.DateTimeField(verbose_name='Inspection Step Start Date-Time')),
                ('step_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection', verbose_name='Step Name')),
                ('uut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Inspection')),
            ],
            options={
                'verbose_name': 'Inspection: Step',
                'verbose_name_plural': 'Inspections: Step',
            },
        ),
        migrations.AddField(
            model_name='staticinspection',
            name='static_inspection_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspectionGroup'),
        ),
        migrations.AddField(
            model_name='proptext',
            name='prop_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection'),
        ),
        migrations.AddField(
            model_name='proptext',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Step'),
        ),
        migrations.AddField(
            model_name='propnumericlimit',
            name='prop_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection'),
        ),
        migrations.AddField(
            model_name='propnumericlimit',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Step'),
        ),
        migrations.AddField(
            model_name='propint',
            name='prop_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection'),
        ),
        migrations.AddField(
            model_name='propint',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Step'),
        ),
        migrations.AddField(
            model_name='propfloat',
            name='prop_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection'),
        ),
        migrations.AddField(
            model_name='propfloat',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Step'),
        ),
        migrations.AddField(
            model_name='propbool',
            name='prop_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspection'),
        ),
        migrations.AddField(
            model_name='propbool',
            name='prop_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.StaticInspectionBool'),
        ),
        migrations.AddField(
            model_name='propbool',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.Step'),
        ),
    ]
