# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20150825_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyinspection',
            name='assemblyTestResults',
        ),
        migrations.RemoveField(
            model_name='assemblyinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='assemblyinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='assemblyinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='assemblytest',
            name='assemblyTestItem',
        ),
        migrations.RemoveField(
            model_name='assemblytest',
            name='part',
        ),
        migrations.RemoveField(
            model_name='cartontemperature',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='cartontemperature',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='cartontemperature',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='neckdiameterinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='neckdiameterinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='neckdiameterinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='outsidediameterinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='outsidediameterinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='outsidediameterinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='partweightinspection',
            name='headCavID',
        ),
        migrations.RemoveField(
            model_name='partweightinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='partweightinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='partweightinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='shotweightinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='shotweightinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='shotweightinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='visioninspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='visioninspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='visioninspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='visioninspection',
            name='visionTestResults',
        ),
        migrations.RemoveField(
            model_name='visiontest',
            name='equipmentID',
        ),
        migrations.RemoveField(
            model_name='visiontest',
            name='visionTestItem',
        ),
        migrations.RemoveField(
            model_name='visualinspection',
            name='defectType',
        ),
        migrations.RemoveField(
            model_name='visualinspection',
            name='headCavID',
        ),
        migrations.RemoveField(
            model_name='visualinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='visualinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='visualinspection',
            name='machineOperator',
        ),
        migrations.RemoveField(
            model_name='volumeinspection',
            name='inspectorName',
        ),
        migrations.RemoveField(
            model_name='volumeinspection',
            name='jobID',
        ),
        migrations.RemoveField(
            model_name='volumeinspection',
            name='machineOperator',
        ),
        migrations.DeleteModel(
            name='assemblyInspection',
        ),
        migrations.DeleteModel(
            name='assemblyTest',
        ),
        migrations.DeleteModel(
            name='assemblyTestCriteria',
        ),
        migrations.DeleteModel(
            name='cartonTemperature',
        ),
        migrations.DeleteModel(
            name='neckDiameterInspection',
        ),
        migrations.DeleteModel(
            name='outsideDiameterInspection',
        ),
        migrations.DeleteModel(
            name='partWeightInspection',
        ),
        migrations.DeleteModel(
            name='shotWeightInspection',
        ),
        migrations.DeleteModel(
            name='visionInspection',
        ),
        migrations.DeleteModel(
            name='visionTest',
        ),
        migrations.DeleteModel(
            name='visionTestCriteria',
        ),
        migrations.DeleteModel(
            name='visualInspection',
        ),
        migrations.DeleteModel(
            name='visualInspectionCriteria',
        ),
        migrations.DeleteModel(
            name='volumeInspection',
        ),
    ]
