# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0006_auto_20151217_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpManNum', models.IntegerField(null=True, verbose_name=b'Employee Man Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmpLMName',
            field=models.CharField(default=b' ', max_length=20, null=True, verbose_name=b'Alias'),
        ),
    ]
