# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20160130_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webappemployee',
            name='EmpManNum',
        ),
        migrations.AddField(
            model_name='webappemployee',
            name='EmpNum',
            field=models.IntegerField(null=True, verbose_name=b'Employee Number'),
        ),
    ]
