# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20160130_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAtWorkstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation', models.CharField(max_length=20, unique=True, verbose_name=b'Job Number')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employees', verbose_name=b'Employee')),
            ],
            options={
                'verbose_name': 'Employee at workstation',
            },
        ),
    ]
