# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employeeatworkstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeatworkstation',
            name='workstation',
            field=models.CharField(max_length=20, unique=True, verbose_name=b'Workstation'),
        ),
    ]
