# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_type',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='product_type',
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_group',
            field=models.ForeignKey(default='c6aabbb8d67d45b686d4c9aa063dfd70', on_delete=django.db.models.deletion.CASCADE, related_name='uut_inspection_log', to='ins.StaticInspectionGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propbool',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_bool', to='ins.Step'),
        ),
        migrations.AlterField(
            model_name='propfloat',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_float', to='ins.Step'),
        ),
        migrations.AlterField(
            model_name='propint',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_int', to='ins.Step'),
        ),
        migrations.AlterField(
            model_name='propnumericlimit',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_numeric', to='ins.Step'),
        ),
        migrations.AlterField(
            model_name='proptext',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_text', to='ins.Step'),
        ),
        migrations.AlterField(
            model_name='staticinspection',
            name='static_inspection_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_step', to='ins.StaticInspectionGroup'),
        ),
        migrations.AlterField(
            model_name='staticinspectionbool',
            name='static_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_bool', to='ins.StaticInspection'),
        ),
        migrations.AlterField(
            model_name='staticinspectionlimit',
            name='static_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_limit', to='ins.StaticInspection'),
        ),
        migrations.AlterField(
            model_name='staticinspectionpart',
            name='inspection_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_parts', to='ins.StaticInspectionGroup'),
        ),
        migrations.AlterField(
            model_name='step',
            name='uut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='ins.Inspection'),
        ),
    ]
