# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
        ('startupshot', '0002_auto_20150721_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='startUpShotWeightLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('susName', models.ForeignKey(db_column=b'susName_id', on_delete=django.db.models.deletion.CASCADE, to='inspection.numericTest', verbose_name=b'Link to inspection name')),
            ],
            options={
                'verbose_name': 'Startup Shot Test Link Name',
                'verbose_name_plural': 'Startup Shot Test Link Name',
            },
        ),
        migrations.AlterField(
            model_name='mattecprod',
            name='jobNumber',
            field=models.CharField(max_length=20, verbose_name=b'Job Number'),
        ),
    ]
